[Jane][1-1-2] 소셜 회원가입 기능 구현
Sc0up/scoup-backend pull request #117
Opened 2021-08-30 10:01 UTC by janeljs

2021-08-30 17:23 UTC, min27604 approved these changes
제인 코드 보면 항상 감탄해요ㅎㅎ 구조도 고려할 게 많으셨을텐데 꼼꼼하기까지 하시구.. 많이 배워요!! 감사합니당☺️ 고생하셨어요!

2021-08-30 17:23 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
> +    default void addOAuthInfo(@MappingTarget User.UserBuilder userBuilder, SignUpRequest signUpRequest) {
찾아보니 예시는 빌더패턴을 쓰지 않아서 타입명만 넣네요.. 찾느라고 고생 많이하셨을 것 같아요..👍

2021-08-30 17:23 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
> +    default void addOAuthInfo(@MappingTarget User.UserBuilder userBuilder, SignUpRequest signUpRequest) {
매핑될 때에는 signUpRequest에 있는 오오스 정보들은 가만있고 여기서 OauthInfo 객체 생성될 때 쓰이고 유저에 들어가는 거 맞나요?

2021-08-30 17:23 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
처음 보는 어노테이션인데 찾아보니 컬렉션을 저장할 때 사용하는 거군요 배워갑니다 ㅎㅎ

2021-08-31 04:55 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
> +    default void addOAuthInfo(@MappingTarget User.UserBuilder userBuilder, SignUpRequest signUpRequest) {
맞아요 예시에서는 빌더를 안 넣고 클래스 이름을 바로 넣길래 왜 안되나 한참 고민했어요ㅋㅋㅋ

2021-08-31 04:56 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
> +    default void addOAuthInfo(@MappingTarget User.UserBuilder userBuilder, SignUpRequest signUpRequest) {
새리의 코멘트를 보고 찾아보니 정확히는 @AfterMapping이 아닌 @MappingTarget이 문제였네요. @MapingTarget에 업데이트하고 싶은 객체를 지정할 수 있는데 객체에 맵핑된 빌더가 있을 경우 빌더가 맵핑에 사용되어 빌더를 받아줘야 하는 거 같아요ㅎㅎ

> MapStruct also supports mapping of immutable types via builders. When performing a mapping MapStruct checks if there is a builder for the type being mapped. This is done via the BuilderProvider SPI. If a Builder exists for a certain type, then that builder will be used for the mappings.

2021-08-31 04:58 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/mapper/UserMapper.java
> +    default void addOAuthInfo(@MappingTarget User.UserBuilder userBuilder, SignUpRequest signUpRequest) {
네 맞아요!ㅎㅎ map 메서드에서는 오오쓰 정보를 사용하지 않다가 `@AfterMapping`으로 맵핑 이후에 User에 업데이트 해줘요ㅎㅎ

2021-08-31 05:02 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
일단은 deleteAll() 메서드 실행 시 발생하는 참조 무결성 제약조건 위반을 막기 위해 EAGER 타입으로 바꿨는데 다른 방법은 없나 더 고민해봐야 할 것 같아요ㅎㅎ

2021-08-31 11:22 UTC, Dae-Hwa reviewed
고생 많으셨습니다~ 어려운거 하고 나니 진행이 확실히 빨라지셨네요 ㅋㅋㅋ!
개선해볼만한 사항들을 남겨봤어요
혹시 이해가 잘 안되는 부분 있으면 남겨주시고 내일 얘기도 해보면 좋을 것 같아요!

2021-08-31 11:22 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/mapper/UserMapperTest.java
>          );
이전에 있던 테스트 케이스도 필요하지 않나요?

2021-08-31 11:22 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +        }
혹시 필요한 이유가 뭔가요?? JPA는 기본생성자를 사용하니 없어도 잘 동작하지 않나요?

2021-08-31 11:22 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/domain/OAuthInfo.java
> +@AllArgsConstructor
작은 도메인이지만 그래도 생성자 따로 만들어주는게 어떨까요 ㅎㅎ

2021-08-31 11:22 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
이런 식으로 사용해야하면 null을 허용하는 방법 이외에 타입이 없는 경우도 enum에 포함시켜주는것도 방법일 것 같은데 어떻게 생각하세요?

2021-08-31 12:05 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
```java
    @AfterEach
    void tearDown() {
        userRepository.deleteAll();
    }
```
여기서 사용되어요!

2021-08-31 12:09 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
제가 만들었던 것 같은데 까먹었네요 🤦‍♂️

2021-08-31 12:09 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
참조무결성 위반이 단순 테스트 코드에서만 일어나는 거면 엔티티에서 조작하는 것 보다 해당 테이블을 먼저 비워주는게 어떨까 싶네요

2021-08-31 12:24 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +                            .oAuthInfo(List.of(new OAuthInfo(OAuthType.GITHUB, "1234567")))
클라이언트한테는 해당 정보를 전송해주지 않는데 제가 잘못 이해한 걸까요?
User에 oAuthInfo를 추가한 건, GITHUB으로 이미 회원가입한 유저가 또 GITHUB으로 회원가입을 하려고 하면 가입을 방지하기 위함이었는데 아직 그 부분 구현이 안 되었네요.

2021-08-31 12:27 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
oAuthInfo는 레파지토리로 관리하고 있지 않은데 어떻게 테이블을 초기화할지 찾아보다가 저런 식으로 처리했어요. findAll로 모든 user를 불러와 해당 컬렉션을 초기화하 하라는 말씀이신가요?

2021-08-31 12:31 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/mapper/UserMapperTest.java
>          );
저는 동일 메서드에 대해서 검증할 필드만 추가되었다고 생각하여 테스트를 수정했는데, 그렇지 않았다면 죄송해요 ㅠㅠ 본의 아니게 코드를 맘대로 수정했네요... 이전에 있던 테스트 케이스가 필요한 이유 부연 설명해주실 수 있을까요?

2021-08-31 12:34 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/OAuthInfo.java
> +@AllArgsConstructor
VO도 도메인인인데 Entity만 생성자 따로 만들어주면 된다고 생각했네요! 수정할게요

2021-08-31 12:36 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +        }
`@Builder` 어노테이션이 붙은 static 메서드를 만들 때 oAuthInfo도 포함한 생성자가 필요해서요!

2021-08-31 12:37 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
레파지토리로 직접 관리하고 있지 않으면 EntityManager를 사용할 수 있지 않을까요?

2021-08-31 12:40 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
`entityManager.clear()` 이렇게요? 그 부분도 고민했는데 일단은 엔티티 매니저 주입 없이 해결해보려고 했어요

2021-08-31 12:41 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +                            .oAuthInfo(List.of(new OAuthInfo(OAuthType.GITHUB, "1234567")))
혹시 생각해보신 케이스가 있나 궁금했어요 ㅎㅎ
만약 필요한 경우가 생기면 Response도 달라져야할텐데 그러면 아예 API도 분리해야 더 좋은 상황이 발생할 수 있지 않을까 하는 생각이 들었어요
너무 설명이 부족했네요

2021-08-31 12:41 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
deleteAll() 말고 그냥 user를 삭제할 때도 참조무결성 제약조건에 위반될 것 같은데 나중에라도 추가되지 않을까요? 혹시 어떻게 생각하세요?

2021-08-31 12:41 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/mapper/UserMapperTest.java
>          );
OAuth 정보가 없는 사용자도 매퍼를 이용해야 하지 않나요??

2021-08-31 12:42 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +        }
다른 방법을 써볼 수 있을 것 같은데 혹시 시간나면 얘기한 번 해봐요 ㅎㅎ 내일 오후에 얘기해봐도 좋을 것 같습니다

2021-08-31 12:43 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/domain/OAuthInfo.java
> +@AllArgsConstructor
생각해보니 VO처럼 사용이 되겠군요 ㅎㅎ 종속되는 테이블을 JPA로 만드는걸 처음봐서 신기하네요 ㅋㅋ 저도 공부좀 해봐야겠네요

2021-08-31 12:44 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/mapper/UserMapperTest.java
>          );
oAuth 정보가 없는 사용자랑 있는 사용자 모두 동일 맵퍼를 사용하고 있어서 같은 경우라고 생각했는데 이런 경우에도 테스트를 분리해야 하는군요. 테스트 기준에 대해 혼동이 있었던 것 같아요. 생각해보니까 다른 테스트에서도 분리하고 있으니 분리하는게 맞는 것 같네요! 커밋기록보고 위에 작성해두셨던 메서드 다시 살려놓을게요

2021-08-31 12:45 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
그 경우는 그때 생각해보는게 좋지 않을까 하는 생각이 들어서요~
지금 예상한거랑 다른 경우가 생긴다면 수정하기가 복잡해지지 않을까 하는 생각이었어요

2021-08-31 12:47 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
그것도 좋네요~! 클라이언트 측에 잘 전달만 하면 될 것 같아요! `NONE` 타입 추가해볼게요ㅋㅋㅋ

2021-08-31 12:48 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
만약에 넣으면 밑에 있는 스트링 벨류도 NotNull로 관리하는게 더 좋을 수도 있을 것 같아요

2021-08-31 12:48 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +                            .oAuthInfo(List.of(new OAuthInfo(OAuthType.GITHUB, "1234567")))
다른 부분은 다 분리되어 있는데 회원가입 API만 저번에 합쳐서 조금 복잡해진 감이 있네요. 이 부분은 내일 더 이야기해봐요~

2021-08-31 12:49 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
더 좋다는 말은 좀 애매하네요 ㅋㅋ 고려해볼 수 있을 것 같습니다

2021-08-31 12:51 UTC, Dae-Hwa requested changes

2021-08-31 12:51 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +    private static Stream<Arguments> socialSignUpProvider() {
접근 제허자 붙이지 않기로 했던 것 같아요!
```suggestion
    static Stream<Arguments> socialSignUpProvider() {
```
테스트케이스가 많아지면 가독성을 위해서 Provider 분리하는 것도 생각해봐야겠네요

2021-08-31 12:56 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
그런데 생각해보니 EntityManager에서 영속성 컨텍스트를 초기화시키더라도 db에는 그대로 데이터가 남아있어 동일한 문제가 발생하지 않나요?

2021-08-31 12:57 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
제가 잘못 생각하는 것일 수도 있으니 시도해볼게요~

2021-08-31 13:00 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
그렇게 말씀하시니 값이 없는데 NONE 타입과 ""와 같은 값을 전달 받는게 좋을지 고민이 되네요😂 null을 허용하지 않고 None 타입이나 비어있는 스트링 등을 받으면 어떤 점이 좋을까요?

2021-08-31 13:03 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +    private static Stream<Arguments> socialSignUpProvider() {
```
- 예외적으로 필드 injection을 사용한다.
    - 접근제어자 없이 만든다.
- 테스트 메소드 이외에 필요한 메소드는 적절한(e.g. private) 키워드를 붙여준다.
```
위와 같이 컨벤션을 정했는데 필드 인젝션이랑 테스트 메서드만 접근 제어자를 없애고 그 이외는 private 붙이기로 한 것 아닌가요?

2021-08-31 13:03 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
저희가 널 체크할 일이 없어지겠죠? ㅋㅋㅋ

2021-08-31 13:04 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
도메인에서는 null이 발생하지 않도록 저희가 만들면 되는데, 요청은 저희가 제한하지 않으면 null일 가능성이 생기는거라 생각해요

2021-08-31 13:09 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +    private static Stream<Arguments> socialSignUpProvider() {
아.. 저는 Provider 메소드까지 테스트 메소드라고 생각했어요
테스트코드에서 직접적으로 사용하는 메소드라서요
내일 다시 얘기해볼까요?

2021-08-31 13:12 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
아하! 저는 여러 개의 요청 필드가 있을 때 필수 필드가 아니면 null을 허용하는 방식으로 구현했었었거든요ㅎㅎ 뭔가 클라이언트쪽에 ""와 같은 값을 채워서 보내달라고 하기가 어색해서(?) 그랬던 것 같아요. 
뭔가 OAuthType까지는 None으로 받는게 좋아보였는데 Id도 ""로 받아야 한다고 생각하니까, 더 많은 필수가 아닌 조건이 들어올 때 비어있는 값을 강제하여 받기보다는 null 처리를 해주는게 낫지 않나?라는 생각이 들었어요. 
프레디는 2개보다 더 많은 optional필드에 대해서도 다 null 허용을 안 하는 식으로 구현하시는지 궁금해요!

2021-08-31 13:18 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
네 저는 웬만하면 null은 허용하지 않도록 개발하는 것 같아요. 꼭 필요한 경우가 아니면요

이유는 위에서 말씀드렸다시피 null인 값이 있으면 어차피 내부적으로 검증 로직이 한 번은 들어가야 하기 때문이고 
둘째로 optional 필드가 과도하게 많으면 api가 잘못 설계된거라고 생각해볼 수 있을 것 같아요

쿼리 스트링으로 검색 조건을 주는 경우는 어쩔수 없이 null을 허용해야했던 것 같아요.

2021-08-31 13:21 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +    private static Stream<Arguments> socialSignUpProvider() {
네 좋아요! 아래 링크에서는 private을 provider에서도 써주는 것 같은데 일반적인 경우는 어떤지 잘 모르겠네요
 https://github.com/eugenp/tutorials/blob/master/testing-modules/junit5-annotations/src/test/java/com/baeldung/junit5/parameterized/StringsUnitTest.java

2021-08-31 13:24 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +    private static Stream<Arguments> socialSignUpProvider() {
저도 일반적인 경우는 잘 모르겠네요
저는 https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-MethodSource 참고하고 작성했던 것 같아요

2021-08-31 13:24 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +    private static Stream<Arguments> socialSignUpProvider() {
제가 생각했던 테스트 메소드 이외의 메소드는 추가적인 로직이 필요한 메소드들을 생각했는데 그게 제대로 얘기가 되지 않았던 것 같네요

2021-08-31 13:37 UTC, Dae-Hwa commented
테이블이랑 컬럼이 o_auth로 만들어지던데 이것도 내일 얘기해봐요 ㅎㅎ 까먹을 것 같아서 커멘트 남겨둡니다

2021-08-31 13:38 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/controller/request/SignUpRequest.java
> +    private OAuthType oAuthType;
저도 에어비앤비랑 이슈트레커에서 쿼리스트링으로 검색조건 줬을 때가 생각나서 그렇게 말씀드렸는데😂 또 그렇군요ㅎㅎ 
저는 클라이언트측에서 같은 dto를 사용하더라도 optional 필드에는 null을 전해주면 된다고 생각했는데 말하다보니 제한하는게 나은 것 같기도...

2021-08-31 13:41 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +    private static Stream<Arguments> socialSignUpProvider() {
공식문서에서는 접근제어자를 안 썼네요! 저도 Baeldung 의존적 개발을 하지 말고 문서를 더 읽어야겠어요ㅋㅋ

2021-08-31 13:41 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/UserAcceptanceTest.java
> +    private static Stream<Arguments> socialSignUpProvider() {
이 부분은 새리도 안 붙이시는 것 같아 제가 수정하는걸로 논의를 마무리하면 될 것 같아요

2021-08-31 13:42 UTC, janeljs commented
> 테이블이랑 컬럼이 o_auth로 만들어지던데 이것도 내일 얘기해봐요 ㅎㅎ 까먹을 것 같아서 커멘트 남겨둡니다

네 이 부분도 고민했는데ㅋㅋㅋ 멘션 감사해요

2021-09-01 08:40 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    private List<OAuthInfo> oAuthInfo = new ArrayList<>();
OAuthUser로 네이밍을 바꾸고 OAuthUsers로 컬렉션의 이름을 변경하였습니다.

2021-09-01 09:16 UTC, Dae-Hwa approved these changes
고생많으셨어요~ 화이팅임다

2021-09-01 09:16 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/auth/OAuthType.java
> +    NONE,
👍👍

2021-09-01 09:16 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/domain/OAuthUser.java
> +    @Column(name = "oauth_type")
어노테이션으로 처리하셨군요,,, 고생 많으셨어요

2021-09-01 09:37 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/domain/User.java
> +    @ElementCollection(fetch = FetchType.EAGER)
제가 이해하기로는 아래와 같은 이유로 현재 상태에서는 해당 어노테이션 없이 delete가 잘 작동하는 것 같아요ㅎㅎ AcceptanceTestBase에서의 데이터베이스 초기화는 더 생각해보아요ㅎㅎ
> NONE 타입과 `""`로 데이터를 채워줘서 해당 객체가 영속 상태가 되어 영속성 컨텍스트 밖에서 delete 쿼리를 날릴 필요가 없어졌다. 하이버네이트는 null인 embedded 객체에 대해 null 참조를 가지고 있기 때문에 기존에는 `OnDeleteAction.CASCADE`가 필요했지만 현재는 OAuthUser가 영속 상태이기 때문에 옵션을 제거하였다.

2021-09-01 09:37 UTC, janeljs commented
새리도 approve 해주셨었어서 머지할게요!

2021-09-01 09:37 UTC, merged