[Freddie][2-2-2] 회원가입 하지 않은 경우 로그인 되지 않도록 수정
Sc0up/scoup-backend pull request #118
Opened 2021-08-31 12:34 UTC by Dae-Hwa

UserNotFoundException을 이용하여 회원가입하지 않은 경우를 처리했습니다.
해당 예외가 User에서만 존재해야할지, 아니면 SignIn에도 있어야 할지 고민이 많았습니다. 그래서 디스커션에도 글을 올려놨었어요.
만약 User에서만 존재해야 한다면 UserService같은 곳에서 NotNull이 보장되는 User를 리턴해주는 메소드가 필요할 것 같았거든요.

일단은 현재 필요한 만큼만 구현하기로 결정하고 최대한 가장 간단한 구조로 작성했습니다.

2021-09-01 04:58 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/signin/exception/UserNotFoundException.java
> +// TODO: 추후에 상속 구조 올바른지 파악 필요. UserNotFound면 User도메인에 속해야 하는게 아닌지?
Discussion에 올려두셨다고 하셨는데 잘 못찾겠네요ㅎㅎ

2021-09-01 05:00 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/signin/exception/UserNotFoundException.java
> +// TODO: 추후에 상속 구조 올바른지 파악 필요. UserNotFound면 User도메인에 속해야 하는게 아닌지?
각각의 예외가 NotFoundException을 상속하게 만들고 도메인이 아닌 전체 프로젝트의 exception 패키지를 만드는 건 어떨까요?

2021-09-01 05:06 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/signin/service/SignInServiceTest.java
> +                .isInstanceOf(UserNotFoundException.class);
`hasMessage`를 추가해서 메시지도 검증하는 건 어떨까요?

2021-09-01 05:07 UTC, janeljs requested changes
고생하셨습니다😊 간단한 코멘트 몇 개 남겨봤어요!ㅎㅎ

2021-09-01 08:36 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/signin/service/SignInServiceTest.java
> +                .isInstanceOf(UserNotFoundException.class);
인수테스트에서 확인하니 그냥 넘어갔는데
추가하는게 더 좋을까요?

2021-09-01 08:52 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/signin/service/SignInServiceTest.java
> +                .isInstanceOf(UserNotFoundException.class);
인수테스트에서 확인하길래 여기서도 확인해야 한다고 생각했는데 생각해보니 그럴 필요 없겠네요ㅎㅎ

2021-09-01 08:52 UTC, janeljs approved these changes

2021-09-02 06:54 UTC, min27604 approved these changes
고생하셨습니다!!!!☺️☺️

2021-09-02 06:54 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/signin/exception/UserNotFoundException.java
> +// TODO: 추후에 상속 구조 올바른지 파악 필요. UserNotFound면 User도메인에 속해야 하는게 아닌지?
생각해보니 이 예외는 토큰으로 유저 정보를 불러올 때에도 사용할 수 있을 것 같아요

2021-09-02 09:14 UTC, merged