[새리][3-2-1] 그룹 수정
Sc0up/scoup-backend pull request #130
Opened 2021-09-08 06:25 UTC by min27604

그룹 수정기능 우선 성공케이스 완료했습니다. 이래저래 삽질을 많이 하다보니 PR 많이 늦어진 점 죄송합니다ㅠㅠ

인터셉터를 사용해 토큰에서 유저 정보를 가져와 setAttribute로 로그인된 유저를 저장합니다.
컨트롤러에서 로그인된 유저 정보가 필요할 때 `@LoggedInUser`를 사용해 저장된 유저를 불러옵니다.
그룹생성과 수정 모두 적용하였습니다.

그룹 인수테스트에서는 미리 생성해둔 아이디값 1, 만료일 2023-01-01T00:00:00.000인 토큰과 테스트 유저를 사용합니다.
인수테스트에서 그룹을 비교시 오너의 필드들은 ignoringFields에 해당하지 않으므로 오너는 따로 비교해주었습니다.

구현하다보니 든 생각인데 처음에 GroupModificationRequest라고 정해놓아서 정해놓았던 crud의 update와 다소 헷갈릴 수 있을 것 같습니다.

2021-09-08 08:22 UTC, janeljs requested changes
일단 에러나는 것 같은 부분에 대해서만 코멘트 남겼어요!ㅎㅎ

2021-09-08 08:22 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
> +                                       .oAuthUsers(new ArrayList<>())
이 부분에 OAuthUser를 안 넣고 빈 array list를 넣어서 테스트 통과가 안 되는 것 같아요!

2021-09-08 08:22 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
> +                                       .oAuthUsers(new ArrayList<>())
해당부분 none타입으로 OAuthUser 생성해서 넣어보시겠어요?

2021-09-08 09:43 UTC, min27604 commented on src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
> +                                       .oAuthUsers(new ArrayList<>())
여전하네요..😭😭😭

2021-09-08 10:41 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
> +                                       .oAuthUsers(new ArrayList<>())
![image](https://user-images.githubusercontent.com/68000537/132495380-01626662-62ce-4e82-81e8-b348e61ac361.png)

이 부분이 문제라고 뜨네요.. 그러게요.. 왜 새리 로컬에서는 되는데 여기선 안 될까용 ㅠㅠ

2021-09-08 10:42 UTC, janeljs requested changes

2021-09-08 10:42 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
> +                                       .oAuthUsers(List.of(OAuthUser.of(OAuthType.NONE, "1")))
NONE일 때는 `""`로 보내주기로 했던 것 같아요!ㅎㅎ

2021-09-08 10:54 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
> +                                       .oAuthUsers(new ArrayList<>())
캐시 지우고 하면 될 듯한데 저도 한 번 볼게요!

2021-09-08 10:55 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
> +                                       .oAuthUsers(new ArrayList<>())
oAuthUsers가 AfterMapping으로 관리되는 것이 문제가 되는 것 같은데 또 로컬에서는 되신다니... 어떤게 문제인지 모르겠네요

2021-09-08 11:14 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
> +                                       .oAuthUsers(new ArrayList<>())
gradle build로 테스트해보니까 에러 뜨네요

2021-09-08 11:25 UTC, Dae-Hwa commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;INIT=CREATE SCHEMA IF NOT EXISTS `scoup`\\;SET SCHEMA scoup;
이 부분 TRUE로 해서 되나 한 번 봐주세요 만약에  이 설정으로 가게되면 로컬 개발할때 초기화가 제대로 안 돼서 힘들 수 있을 것 같아요

2021-09-08 11:25 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/group/GroupAcceptanceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
여기서 넣어준게 문제가 됐을 것 같아요
다른 인수 테스트의 afterEach에 있는 deleteAll을 beforeEach로 옮겨주니 잘 되네요

2021-09-14 16:37 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/config/WebConfig.java
> +    private static final String[] PATH_TO_EXCLUDE = {"/sign-in/**", "/oauth/**", "/users/**", "/h2-console/**"};
프레디 의견 감사합니다!! path로 뺄 지 아니면 커스텀 어노테이션을 설정해서 로그인이 필요한 부분에 적용할지 고민했는데 혹시 어노테이션 활용하는 건 어떻게 생각하세요? path가 나을 것 같다 생각하시면 말씀하신대로 수정하려구요 ㅎㅎ 제인 의견도 궁금해요! @janeljs

2021-09-15 01:06 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/config/WebConfig.java
> +    private static final String[] PATH_TO_EXCLUDE = {"/sign-in/**", "/oauth/**", "/users/**", "/h2-console/**"};
저는 원래 메서드 단위로 어노테이션을 정의하여 사용했었는데 그랬더니 거의 모든 메서드에 해당 어노테이션이 붙어서 조금 지저분하기도 하더라구요! 그런데 저렇게 path 단위로 관리할거면 어노테이션 적용 범위를 클래스로 설정해서 만드는 것도 좋을 것 같아요!ㅎㅎ

2021-09-15 01:10 UTC, janeljs approved these changes
새리 고생하셨습니다!🥰

+) 코드리뷰 반영할 때 커밋 메시지에 해당 리뷰 링크 참고하기로 했던 거 다음부터는 반영해주시면 좋을 것 같아요ㅎㅎㅎ

2021-09-16 17:02 UTC, janeljs approved these changes

2021-09-19 11:40 UTC, Dae-Hwa approved these changes
고생 많으셨습니다~!

2021-09-19 12:03 UTC, janeljs approved these changes

2021-09-19 12:03 UTC, merged