[Freddie][4-10-1] 일정 후보 월별 전체 조회
Sc0up/scoup-backend pull request #171
Opened 2021-09-23 03:24 UTC by Dae-Hwa

일정 후보를 범위 조회 해서 월별로 묶어줍니다. 

범위조회 검증때문에 테스트 코드가 길어졌는데 추후 리팩토링하면서 Provider 클래스로 빼도록 하겠습니다.

2021-09-24 04:13 UTC, janeljs requested changes

2021-09-24 04:13 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
> +public class Schedule extends BaseEntity {
제가 곧 PR드릴 엔티티랑 많은 부분이 충돌날 것 같은데 마음의 대비하고 있을게요ㅋㅋㅋ

2021-09-24 04:13 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
> +        schedule.addScheduleCandidates(scheduleCandidates);
이렇게 구현하신 이유가 있나요? 저는 개인적으로 엔티티 내부 컬렉션은 필드에서 초기화하고 하이버네이트가 관리한 이후에는 교체하지 않는 것이 좋다고 생각해서 이렇게 했는데 프레디는 어떤 생각으로 이렇게 하셨는지 궁금해요!
+) 이렇게 해도 빌더에서 해당 값을 넣어주지 않으면 필드에서 초기화한 어레이 리스트 대신 null이 들어가는 것 같은데 혹시 같은 문제 겪어보셨나용,,,

2021-09-24 04:13 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/schedule/domain/ScheduleCandidate.java
> +    private boolean isConfirmed;
이 부분이 애매하네요... ConfirmedScheudle이 따로 존재하는 구조에서 ScheduleCandidate 엔티티 상에서 해당 컬럼이 필요할지? 뭔가 DTO 변환 단계에서 isConfirmed를 추가해도 될 것 같아요. 나머지 필드는 제가 만든 엔티티랑 비슷한 것 같은데 일단 PR 보내고 충돌 해결하면서 더 생각해볼게요ㅋㅋㅋ 이번 작업은 많이 겹치네요.

2021-09-24 04:13 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/schedule/repository/ScheduleCandidateRepository.java
> +    @Query("SELECT sc " +
저희 이제 약간 복잡한 쿼리도 탄생하는 것 같은데 querydsl로 이전해볼까요? (이번 pr에서 하시라는 건 아니고 건의사항이에요!)

2021-09-24 04:13 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/schedule/service/ScheduleCandidateService.java
> +
줄이 한 줄 더 있는 것 같아요😂

2021-09-24 04:13 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
> +    private static String TEST_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjcyNDk4ODAwfQ.DXojMeUGIq77XWvQK0luZtZhsi-c6s9qjiiu9vHhkbg";
이 부분 저는 TestDataSetup 클래스로 분리했는데 얼른 정리해서 PR드릴게요ㅎㅎ

2021-09-24 04:13 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
> +                        ScheduleCandidateReadAllResponses.from(
진짜 depth가 깊어질 수록 형태를 알기 힘들긴 하네요ㅠㅠ 프레디가 말씀하셨던게 뭔지 알겠어요.

2021-09-24 04:13 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateDatabaseHelper.java
> +public class ScheduleCandidateDatabaseHelper {
helper 패키지도 새로 만들까요?

2021-09-24 04:13 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/schedule/repository/ScheduleCandidateRepositoryTest.java
> +                    "범위 안쪽이면서 오른쪽으로 벗어나게",
와우...고생하셨습니다

2021-09-24 04:13 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/schedule/repository/ScheduleCandidateRepositoryTest.java
> +                outerRange.get()
👏👏👏

2021-09-24 05:51 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
> +        schedule.addScheduleCandidates(scheduleCandidates);
혹시 상황 좀 더 상세하게 적어주실 수 있나요?
default 어노테이션으로 해결 가능할 듯 하네요

2021-09-24 05:57 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
> +        schedule.addScheduleCandidates(scheduleCandidates);
이렇게 구현한 이유는 말씀하신것 처럼 초기화가 한 번 됐으니 건드리지 않는게 안전하다고 판단해서였습니다. 사실 빌더라 영향은 없을 것 같긴하네요

2021-09-24 06:00 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/domain/ScheduleCandidate.java
> +    private boolean isConfirmed;
네 ConfirmedScheudle를 고려하지 않아서 일단 넣어놨습니다. 새로운 테이블로 관리하면 굳이 필요 없을 것 같네요

2021-09-24 06:00 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/repository/ScheduleCandidateRepository.java
> +    @Query("SELECT sc " +
ㅋㅋ 네 아직 동적 쿼리는 아니라서 조금 이른 감이 있긴 한데, 조회조건이 점점 복잡해질테니 필요해질 것 같긴 해요

2021-09-24 06:01 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
> +    private static String TEST_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjcyNDk4ODAwfQ.DXojMeUGIq77XWvQK0luZtZhsi-c6s9qjiiu9vHhkbg";
네 일단 구현한대로 편하게 합쳐주시고 다른 pr에서 세팅 잡으면 좋을 것 같습니다.

2021-09-24 06:09 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
> +                        ScheduleCandidateReadAllResponses.from(
단점은 모니터가 커야된다는건데... 더 좋은 방법 있으면 적용해보는 것도 좋을 것 같습니다. ㅋㅋㅋ

2021-09-24 06:09 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateDatabaseHelper.java
> +public class ScheduleCandidateDatabaseHelper {
EntityManager 관리해주는 클래스를 만드는건 어떻게 생각하세요?

2021-09-24 06:09 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
> +    @ColumnDefault("'" + DEFAULT_COLOR_CODE + "'")
네 ㅎㅎ 그런데 따옴표가 기본으로 붙는 설정때문에 살짝 지저분해지네요 ㅠㅠ

2021-09-24 06:09 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateReadAllResponse.java
> +    private long id;
클라이언트에서 id를 기준으로 조회할 일이 생길수도 있을거라 생각했습니다.

2021-09-24 06:09 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/controller/request/ScheduleCandidateReadRequest.java
> +    private LocalDate endDate;
endDate에도 NotNull이 들어가야겠네요 수정하겠습니다

2021-09-24 06:09 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/controller/ScheduleCandidateController.java
> +    public ScheduleCandidateReadAllResponses readAll(@PathVariable long groupId, ScheduleCandidateReadRequest givenScheduleCandidateReadRequest) {
여기서는 groupId가 null이 될 일이 없으니 원시타입으로 설정했어요. 이유는 groupId가 null이면 애초에 유효한 주소로 요청이 오지 않을거라 생각했습니다.
그리고 request dto나 entity에서는 id가 null일 경우가 생기지만, response에서는 id가 없다는 말은 조회 자체가 되지 않았으니 id가 빈 response객체는 생성 될 일이 없다고 생각했습니다.

2021-09-24 06:09 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/controller/ScheduleCandidateController.java
> +    public ScheduleCandidateReadAllResponses readAll(@PathVariable long groupId, ScheduleCandidateReadRequest givenScheduleCandidateReadRequest) {
여기서는 groupId가 null이 될 일이 없으니 원시타입으로 설정했어요. 이유는 groupId가 null이면 애초에 유효한 주소로 요청이 오지 않을거라 생각했습니다.
그리고 request dto나 entity에서는 id가 null일 경우가 생기지만, response에서는 id가 없다는 말은 조회 자체가 되지 않았으니 id가 빈 response객체는 생성 될 일이 없다고 생각했습니다.

2021-09-24 06:09 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/controller/request/ScheduleCandidateReadRequest.java
> +    private LocalDate endDate;
endDate에도 NotNull이 들어가야겠네요 수정하겠습니다

2021-09-24 06:09 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/controller/response/ScheduleCandidateReadAllResponse.java
> +    private long id;
클라이언트에서 id를 기준으로 조회할 일이 생길수도 있을거라 생각했습니다.

2021-09-24 06:10 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
> +    @ColumnDefault("'" + DEFAULT_COLOR_CODE + "'")
네 ㅎㅎ 그런데 따옴표가 기본으로 붙는 설정때문에 살짝 지저분해지네요 ㅠㅠ

2021-09-25 06:48 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateDatabaseHelper.java
> +public class ScheduleCandidateDatabaseHelper {
좋은 것 같습니다👍

2021-09-26 04:11 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
> +        schedule.addScheduleCandidates(scheduleCandidates);
```java
    protected Group(String name, String description, User owner) {
        this.name = name;
        this.description = description;
        this.owner = owner;
    }

    @Builder
    public static Group of(String name, String description, User owner, List<Schedule> schedules) {
        Group group = new Group(name, description, owner);
        group.addSchedules(schedules);
        return group;
    }
```
```java
    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext context) throws Exception {
        return Stream.of(
                Arguments.of(
                        "성공",
                        GroupCreationRequest.builder()
                                            .name("group name")
                                            .description("description")
                                            .build(),
                        Group.builder()
                             .name("group name")
                             .description("description")
                             .schedules(new ArrayList<>())
                             .owner(User.builder()
                                        .nickname("nickname")
                                        .email("email@email.com")
                                        .password("password")
                                        .avatarUrl("url")
                                        .username("username")
                                        .oAuthUsers(List.of(OAuthUser.of(OAuthType.NONE, "")))
                                        .build())
                             .build()
                )
        );
    }
```
위와 같은 상황에서 ` .schedules(new ArrayList<>())` 부분이 없으면 오류가 나는 상황입니다.

2021-09-26 04:19 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/schedule/controller/ScheduleCandidateController.java
> +    public ScheduleCandidateReadAllResponses readAll(@PathVariable long groupId, ScheduleCandidateReadRequest givenScheduleCandidateReadRequest) {
@Dae-Hwa 그러면 `@PathVariable`이나 response dto에서는 primitive type을 사용하시고 `@queryParam`이나 request dto, entity에서는 wrapper type을 사용하신다고 이해해도 될까요?ㅎㅎ

2021-09-26 04:20 UTC, janeljs approved these changes

2021-09-26 06:37 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/controller/ScheduleCandidateController.java
> +    public ScheduleCandidateReadAllResponses readAll(@PathVariable long groupId, ScheduleCandidateReadRequest givenScheduleCandidateReadRequest) {
네 대체로 그런데, null인 경우가 필요할지를 생각해보는 것 같아요 ㅋㅋ
단순화시키면 제인이 말씀하신게 맞겠네요

2021-09-26 06:46 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
> +        schedule.addScheduleCandidates(scheduleCandidates);
```
public static class ScheduleBuilder {
    private String title;
    private String description;
    private LocalDateTime dueDateTime;
    private String colorCode;
    private List<ScheduleCandidate> scheduleCandidates;

        ...
```

롬복이 만들어주는 빌더가 이렇게 생겨서 그런 것 같아요

클래스에 빌더 어노테이션이 없으니 Default 어노테이션은 사용 불가능한 것 같습니다. 그러면

![image](https://user-images.githubusercontent.com/24666330/134796843-2fb39520-7f28-4daf-9b2d-46dfda3be338.png)

이런 식으로 처리해줄 수 있을 것 같아요

2021-09-26 09:42 UTC, min27604 approved these changes
사실 이전 PR에서 조금 이해하기 어려운 부분이 있었는데 이번 PR에서 다 이해가 된 것 같아요 ㅎㅎ 테스트 짜시느라 고생 많으셨을 것 같아요 수고하셨습니다!!

2021-09-26 09:42 UTC, min27604 commented on src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
> +                                                                                .endDateTime(readAllTestData.scheduleCandidate1().getEndDateTime())
startDateTime과 endDateTime만 `readAllTestData.scheduleCandidate1()`에서 가져오는 이유가 따로 있으신가요?

2021-09-26 09:47 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/schedule/ScheduleCandidateAcceptanceTest.java
> +                                                                                .endDateTime(readAllTestData.scheduleCandidate1().getEndDateTime())
같은 결과가 나와야 하니 이렇게 해뒀습니다. 다소 일관성이 없어보이는데 provider를 분리하는 작업을 하며 개선해보겠습니다

2021-09-26 09:47 UTC, merged

2021-09-26 22:59 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/schedule/domain/Schedule.java
> +        schedule.addScheduleCandidates(scheduleCandidates);
`@Singular` 어노테이션을 이용하여 해결하였습니다.
https://github.com/Sc0up/scoup-backend/discussions/174