[Jane] 소셜 서비스에 가입된 사용자 정보 요청
Sc0up/scoup-backend pull request #22
Opened 2021-08-10 04:43 UTC by janeljs

### 전달 사항
- 소셜 서비스에 가입된 사용자의 정보를 요청하는 기능 구현이 완료되었습니다.
- 아직 GitHub만 구현된 상태이며 카카오, 구글 OAuth 구현을 하면서 OAuthType을 추가해보겠습니다.
- 현재 GitHugOAuth가 OAuth 인터페이스를 구현하고 있는데 KakaoOAuth, GoogleOAuth와 같은 구현체를 추가하면 될 것 같습니다.

#### 기타
- `spring.jackson.property-naming-strategy=SNAKE_CASE`와 같이 설정해준 것이 webclient에도 적용되지 않는지 access token 요청 과정에서 자꾸만 BAD_REQUEST 에러가 발생하여 문제의 원인을 파악하는데 오랜 시간이 걸렸습니다. 
- `@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)`를 DTO에 추가해주니까 정상작동하네요.

2021-08-10 05:35 UTC, Dae-Hwa commented
```java
ExchangeStrategies strategies = ExchangeStrategies
            .builder()
            .codecs(clientDefaultCodecsConfigurer -> {
                clientDefaultCodecsConfigurer.defaultCodecs().jackson2JsonEncoder(new Jackson2JsonEncoder(new ObjectMapper(), MediaType.APPLICATION_JSON));
                clientDefaultCodecsConfigurer.defaultCodecs().jackson2JsonDecoder(new Jackson2JsonDecoder(new ObjectMapper(), MediaType.APPLICATION_JSON));

            }).build();

    WebClient webClient = WebClient.builder().exchangeStrategies(strategies).build();
```

2021-08-10 11:55 UTC, min27604 approved these changes
고생많으셨어요🥰

2021-08-11 04:19 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/user/auth/response/OAuthUserResponse.java
> +    private String avatarUrl;
리소스 서버마다 형태가 다를 것 같은데 혹시 그렇게되면 이 부분은 어떻게 될까요?

2021-08-11 04:49 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/response/OAuthUserResponse.java
> +    private String avatarUrl;
아마 dto를 GitHubUserResponse와 같은 식으로 따로 만들어야 할 것 같아요!

2021-08-11 05:58 UTC, Dae-Hwa requested changes
제인 고생 많으셨어요~

진짜 리뷰가 10개가 돼버렸네요~ ㅎㅎㅎㅎㅎㅎ 화이팅입니다.

어제 말했던 컴포넌트가 이상해보인다는 것도 이유를 찾아서 리뷰에 남겨뒀습니다!

이상하면 질문 주세요~ 고생많으셨습니다.

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/GitHubOAuth.java
> +    private final String clientSecret;
PropertySource를 이용해서 분리해볼 수 있을 것 같아요

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/resources/application.properties
> +spring.profiles.include=auth, key
프로필을 이상하게 사용하고 있는 것 같아요

저희도 프로필을 고려해봐야겠지만, 프로필을 사용하는 경우는

Test나 Dev같은 프로필에서는 
`logging.level.com.postsquad.scoup=DEBUG`
설정을 해두고
Prod같은 프로필에서
`logging.level.com.postsquad.scoup=WARN`
과 같이

같은 설정을 프로필에 따라서 다르게 사용하기 위해 사용하는 경우가 일반적인 것 같습니다.

같은 이유로 프로퍼티 파일의 이름도 바꿔주는게 좋을 것 같습니다.
보통 .을 구분자로 사용했던 것 같아요
`auth.github.properties` 와 같은 방식으로요.

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/resources/application.properties
> +logging.level.com.postsquad.scoup=DEBUG
지금은 이렇게 해도 무관하겠지만, 나중에 프로필에 따라서 바뀌게 설정되도록 하는게 좋을 것 같아요

그리고 그렇게 되야하는걸 다 같이 알아야 하니 이슈로 적어주셨으면 좋았을 것 같습니다.

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/config/WebConfig.java
> +        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE);
이 부분 없어도 잘 동작하는 것 같아요.
ObjectMapper가 이미 빈으로 관리되고 있어서 그런 것 같습니다.

그리고 혹시 copy를 해준 특별한 이유가 있나요?

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/exception/AccessTokenNotFoundException.java
> +import com.postsquad.scoup.web.user.auth.exception.OAuthException;
불필요한 import 같아요.
이외에도 꽤 많은 것 같은데 정리해주세요~!

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/exception/AccessTokenNotFoundException.java
> +import com.postsquad.scoup.web.user.auth.exception.OAuthException;
이런 경우는 커밋 메세지에 참조 남기지 않아도 될 것 같네요! ㅎㅎ

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/GitHubOAuth.java
> +                .orElseThrow(GitHubUserNotFoundException::new);
여기서 에러가 나는 경우는 클라이언트에 어떻게 전달되나요?

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/response/OAuthUserResponse.java
> +    private String avatarUrl;
이런 부분은 추상화해서 공통적인 리스폰스를 보내주는게 괜찮을 것 같습니다.
다만, 도메인 객체의 경우는 따로 분리하면 좋을 것 같고, 
리스폰스에는 어떤 리소스 서버를 사용하는지 구분자가 들어가긴 해야할 것 같습니다.

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
> +    }
제가 생각할때는 User의 리소스를 가져오는게 아닌 것 같아요.

제가 생각하는 User 도메인은 저희 서비스에 가입한 사용자인데, 

지금 API에서는 아직 회원가입이 되어 있지 않기 때문에 User가 아닌 것 같습니다.

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
> +    }
oauth 전반적인 패키징도 비슷한 생각입니다.

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
이제 없어도 되지 않나요?

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +    private final String code;
```suggestion
    private final String clientId;
    
    private final String clientSecret;
    
    private final String code;
```

DTO는 이런 식으로 하기로 했던 것 같아요

2021-08-11 05:58 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/service/UserService.java
> +        String token = "token";
임시로 넣어둔건지 몰라서 일단 남깁니다.

상수로 관리하는 부분이 있었던 것 같은데, 겹치는 부분이 있으면 공통적으로 관리하는 것을 생각해봐도 될 것 같아요.
그리고 상수로 관리하는 부분 바깥에서 사용되는 부분이 또 있다면, 클래스의 응집성이 조금 떨어지는게 아닌가 하는 의심을 해볼 수 있을 것 같습니다.

2021-08-11 05:59 UTC, Dae-Hwa commented
나중에 충돌나는 부분도 깃헙에서 바로 해결하지 마시고, 
작업한뒤 커밋 해주시면 같이 봐드리겠습니다

2021-08-11 12:09 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/response/OAuthUserResponse.java
> +    private String avatarUrl;
@min27604 @Dae-Hwa 지금은 `SocialAuthenticationResponse`라는 클래스에서 공통 리스폰스를 보내주고 있는데 이것 외에 새로운 클래스를 정의하는게 좋을까요? `GitHubUserResponse`의 경우에는 리소스를 받아올 때 사용할 DTO라서 각 리소스 서버마다 정의해주고, 클라이언트에게 주는 응답 포맷만  `SocialAuthenticationResponse`로 통일하면 된다고 생각했는데 더 나은 방법이 있다면 제안 부탁드려요!


+) PR메시지에서 언급드렸듯이 소셜 서비스 별 구분자는 추가하려고 생각하고 있었어요ㅎㅎ
>아직 GitHub만 구현된 상태이며 카카오, 구글 OAuth 구현을 하면서 OAuthType을 추가해보겠습니다.

2021-08-11 12:48 UTC, janeljs commented on src/main/resources/application.properties
> +spring.profiles.include=auth, key
보통 구분자로 `.`을 사용하는 군요! 해당 부분 수정하겠습니다.
`spring.profiles.include=auth, key`로 설정하지 말고 `@PropertySource`를 이용하여 auth와 key에 관련된 설정파일을 가져오는 것으로 이해했는데 맞을까요?

2021-08-11 12:50 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/config/WebConfig.java
> +        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE);
ObjectMapper의 설정을 복사해서 web client에만 등록해주려고 했는데 생각해보니까 전역으로 설정을 관리하고 있어 필요없는 부분이네요! 해당 부분 제거하겠습니다.

2021-08-11 12:51 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/exception/AccessTokenNotFoundException.java
> +import com.postsquad.scoup.web.user.auth.exception.OAuthException;
패키지를 변경한 뒤에 다시 확인을 못했네요! 한 번 더 검토할게요!

2021-08-11 12:56 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
> +    }
@Dae-Hwa 방금 확인했는데 백엔드 용어 정리 시트에 소셜 서비스에 가입한 사용자 정보에 대한 용어 정의는 없네요! `OAuthUserData` 정도는 어떠세요? 좋은 네이밍 있으면 제안 부탁드려요🙂 패키지는 현재 web>user>auth로 되어있는데 web>auth로 변경해볼까 하는데 괜찮을까요?

2021-08-11 12:57 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
다른 클래스에서는 제거했는데 이 부분 제거하는 걸 놓쳤네요! 지적 감사합니다.

2021-08-11 13:01 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +    private final String code;
앗 저는 몰랐는데 그렇게 하기로 했군요! 컨벤션에 추가해놓았습니다~ 혹시 엔티티와 DTO 사이에 줄바꿈 규칙을 다르게 가져가는 이유가 있을까요? 상의했었는데 제가 놓친 거라면 죄송해요😥

2021-08-11 13:05 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/service/UserService.java
> +        String token = "token";
GitHubOAuth 클래스에서 해당 부분을 상수로 관리하고 있는데요.
```java
    private static final String TOKEN = "token";
```
저 부분은 클라이언트에서 로그인이 구현될 경우 삭제되는 부분인데 테스트 작성을 위해 임시로 구현한 부분이라 지역변수로 처리했던 것 같습니다.  OAuth 서비스 쪽으로 이동해볼 수 있을 것 같아요.

2021-08-11 13:07 UTC, janeljs commented
> 나중에 충돌나는 부분도 깃헙에서 바로 해결하지 마시고,
> 작업한뒤 커밋 해주시면 같이 봐드리겠습니다

네 다시 리뷰 요청드리겠습니다.
추가로 아래 부분에 대한 코멘트를 못 찾겠는데 다시 한 번 확인 부탁드려요!
> 어제 말했던 컴포넌트가 이상해보인다는 것도 이유를 찾아서 리뷰에 남겨뒀습니다!

감사합니다🙂

2021-08-11 13:09 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/GitHubOAuth.java
> +                .orElseThrow(GitHubUserNotFoundException::new);
해당 에러를 잡는 exception handler를 추가하여 에러 메시지와 함께 BAD_REQUEST라는 상태코드를 전달해주면 될 것 같습니다.

2021-08-11 13:20 UTC, Dae-Hwa commented on src/main/resources/application.properties
> +spring.profiles.include=auth, key
네 그런식으로 클래스 단위 구분을 하셔도 좋고, 아니면 path를 직접 지정해서 불러올 수도 있어요.
이외에도 방법은 많다고 알고 있습니다.

2021-08-11 13:22 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/GitHubOAuth.java
> +                .orElseThrow(GitHubUserNotFoundException::new);
이번 pr에 포함되는게 좋을까요??

2021-08-11 13:23 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
> +    }
네이밍은 조금 더 고민해볼게요
패키지는 저도 비슷한 생각했는데,
관련해서 api  path도 조금 생각해볼만 한 것 같더라고요
내일쯤 이슈로 정리해서 올려볼게요

2021-08-11 13:24 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +    private final String code;
저번에 이노가 이렇게 하셔서 습관됐다고 했던 것 같은데
제가 잘못 알아들었나봐요 🤦‍♂️
어떻게 하는게 좋을까요?
그리고 저는 엔티티도 저렇게 작성했던 것 같네요
어노테이션이 많아서 그렇기도 했지만

2021-08-11 13:24 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/GitHubOAuth.java
> +                .orElseThrow(GitHubUserNotFoundException::new);
음..이 리뷰만 예외로 다시 pr을 드리도록 할게요😁

2021-08-11 13:26 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
> > 나중에 충돌나는 부분도 깃헙에서 바로 해결하지 마시고,
> > 작업한뒤 커밋 해주시면 같이 봐드리겠습니다
> 
> 네 다시 리뷰 요청드리겠습니다.
> 추가로 아래 부분에 대한 코멘트를 못 찾겠는데 다시 한 번 확인 부탁드려요!
> 
> > 어제 말했던 컴포넌트가 이상해보인다는 것도 이유를 찾아서 리뷰에 남겨뒀습니다!
> 
> 감사합니다🙂
---
https://github.com/Sc0up/scoup-backend/pull/22#discussion_r686515677

이 부분이었어요

User에 OAuth가 포함되는게 아니라 새로운 패키지 단위가 되어야 하는게 아니었나 하는 생각이었습니다!

2021-08-11 13:49 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +    private final String code;
앗 그건 클래스랑 첫번째 필드 사이에 한 줄 띄는거 말씀드린 거였어요😂

2021-08-11 13:49 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +    private final String code;
그럼 깔끔하게 다 띄는 걸로해요😁

2021-08-11 13:52 UTC, janeljs commented
> > > 나중에 충돌나는 부분도 깃헙에서 바로 해결하지 마시고,
> > > 작업한뒤 커밋 해주시면 같이 봐드리겠습니다
> > 
> > 
> > 네 다시 리뷰 요청드리겠습니다.
> > 추가로 아래 부분에 대한 코멘트를 못 찾겠는데 다시 한 번 확인 부탁드려요!
> > > 어제 말했던 컴포넌트가 이상해보인다는 것도 이유를 찾아서 리뷰에 남겨뒀습니다!
> > 
> > 
> > 감사합니다🙂
> 
> [#22 (comment)](https://github.com/Sc0up/scoup-backend/pull/22#discussion_r686515677)
> 
> 이 부분이었어요
> 
> User에 OAuth가 포함되는게 아니라 새로운 패키지 단위가 되어야 하는게 아니었나 하는 생각이었습니다!

앗  저는 컴포넌트랑 서비스 어노테이션에 관한 논의 말씀하시는 것인줄 알았네요ㅎㅎ OAuth가 User에 포함되는게 아니라는 말씀이시죠? 해당부분은 일단 위 코멘트에서처럼 수정해볼게요ㅎㅎ

2021-08-11 13:59 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +    private final String code;
네 좋습니다 @min27604 괜찮으신가요?

2021-08-11 16:29 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/user/auth/request/AccessTokenRequest.java
> +    private final String code;
네 저는 좋습니다

2021-08-11 16:43 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/response/OAuthUserResponse.java
> +    private String avatarUrl;
> @min27604 @Dae-Hwa 지금은 `SocialAuthenticationResponse`라는 클래스에서 공통 리스폰스를 보내주고 있는데 이것 외에 새로운 클래스를 정의하는게 좋을까요? `GitHubUserResponse`의 경우에는 리소스를 받아올 때 사용할 DTO라서 각 리소스 서버마다 정의해주고, 클라이언트에게 주는 응답 포맷만 `SocialAuthenticationResponse`로 통일하면 된다고 생각했는데 더 나은 방법이 있다면 제안 부탁드려요!
> 
> +) PR메시지에서 언급드렸듯이 소셜 서비스 별 구분자는 추가하려고 생각하고 있었어요ㅎㅎ
> 
> > 아직 GitHub만 구현된 상태이며 카카오, 구글 OAuth 구현을 하면서 OAuthType을 추가해보겠습니다.

저도 같은 의견이에요!

2021-08-11 21:02 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/GitHubOAuth.java
> +    private final String clientSecret;
아직도 이해가 좀 덜 되었는데요!😂 앞으로 GitHubOAuth 외에도 GoogleOAuth, KakaoOAuth 가 생길텐데 이걸 `GitHubOAuthProperty`와 `GitHubOAuth`로 분리하는 식으로 해서 6개의 클래스를 만드는 게 좋다고 생각하신 건지 다시 여쭤보아요! 저는 개인적으로 해당 필드들이 각 서비스에서 필요한 자원을 요청할 때만 쓰이고 있고, 이미 각 정보들은 하드코딩이 아니라 따로 관리하고 있는 설정 파일에서 주입받고 있기 때문에 굳이 클래스 분리가 필요한가 싶어요.

2021-08-11 21:39 UTC, janeljs commented
@Dae-Hwa 전반적으로 코멘트 주신 부분 반영하였고, OAuthType과 ErrorResponse, exceptionHandler 관련해서는 새로운 PR을 열게요! [클래스 분리](https://github.com/Sc0up/scoup-backend/pull/22#discussion_r686824810) 관련해서는 아직 이해가 덜 된 부분이 있어 진행하지 못했는데, 이것도 코멘트 남겨주시면 구글, 카카오 서비스를 추가하며 다음 pr에서 반영해볼 수 있을 것 같아요😄

검토하시고 이상없으시면 merge 부탁드릴게요!

2021-08-12 05:42 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/auth/GitHubOAuth.java
> +    private final String clientSecret;
클래스 관점에서 책임이 너무 많은 것 같아서 말씀드렸어요
분리의 필요성이 지금 없다면 하지 않아도 되지만 언젠가는 하게 될 것 같아서요

더군다나 해당 클래스가 서비스 성격을 띠는데 그렇다면 더더욱 프로퍼티를 서비스 내부에 직접 관리하는건 좋지 않다고 봐요.
그렇게 치면 도메인 같은것도 나누지 않고 해당 서비스 내부에 모든 로직이 담기면 되는거잖아요?

그럼에도 납득이 잘 되지 않는다면 일단 넘어가고 나중에 다시 생각해보도록 해요~!

2021-08-12 06:06 UTC, Dae-Hwa requested changes

2021-08-12 06:06 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/response/SocialAuthenticationResponse.java
>      private String avatarUrl;
어제 정한 컨벤션이랑 조금 다른 것 같네요 ㅎㅎ 😂

2021-08-12 06:07 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/auth/service/OAuthService.java
> +        OAuthUserResponse oAuthUserInfo = oauth.getOAuthUserInfo(token.getAccessToken());
이 부분은 기능상 문제는 없으니 반드시 지금 고쳐야 하는건 아닌데,
OAuth 부분의 클래스 설계가 조금 아쉬워서요

2021-08-12 06:36 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/controller/response/SocialAuthenticationResponse.java
>      private String avatarUrl;
앗 뭐지...ㅠㅠ 이거 프레디가 suggest해주신거 메시지 적어서 커밋하려니까 outdated되었다고 나와서 이미 반영된 줄 알았는데..바로 수정할게요!

2021-08-12 07:46 UTC, Dae-Hwa approved these changes

2021-08-12 07:46 UTC, merged

2021-08-12 07:47 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/auth/GitHubOAuth.java
> +    private final String clientSecret;
잘 설명해주신 덕분에 이해가 되었습니다!👍 이번 pr의 단위가 너무 커지는 것 같아 다음 pr에서 해당 부분 반영해서 다시 리뷰 요청할게요~

2021-08-12 07:48 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/auth/service/OAuthService.java
> +        OAuthUserResponse oAuthUserInfo = oauth.getOAuthUserInfo(token.getAccessToken());
OAuth 부분의 클래스 설계에 대해서는 더 고민해보고 수정한다음 다음 PR 때 리뷰 요청할게요! 해당 부분 OAuth 내부로 이동해보겠습니다.