[새리] 이메일 중복확인
Sc0up/scoup-backend pull request #28
Opened 2021-08-10 17:01 UTC by min27604

이메일 중복확인 구현 완료했습니다. 간단한 로직이지만 이래저래 많이 헤매서 시간이 다소 오래 걸린 점 양해 부탁드립니다.
- 이메일 중복확인
- 이메일 유효성 검사

먼저 메인에 머지된 브랜치(이메일 회원가입)를 미리 가져와서 충돌해결을 하긴 했습니다만.. 해당 부분 한 번 더 살펴주시면 감사하겠습니다.☺️

2021-08-10 19:09 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
> +        return ErrorResponse.of(
위에 메서드에도 적용되는 부분인데 Builder를 사용하면 어떨까요?😯

2021-08-10 19:26 UTC, janeljs approved these changes
새리 고생 많으셨습니다👍 몇 가지 코멘트 남기긴 했는데 사소한 것들이라 approve 할게요!

2021-08-10 19:26 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
> +    public static ErrorResponse of(HttpStatus status, Set<ConstraintViolation<?>> errors) {
위에 메서드에도 적용되는 부분인데 Builder를 사용하면 어떨까요?😯

2021-08-10 19:26 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/error/controller/response/ErrorResponse.java
> +                        .map(constraintViolation -> constraintViolation.getPropertyPath() + ": " + constraintViolation.getMessage())
👍👍👍

2021-08-10 19:26 UTC, janeljs commented on src/main/java/com/postsquad/scoup/web/user/repository/UserRepository.java
> +    Optional<User> findByEmail(String email);
한 줄 띄면 더 좋을 것 같아요❤

2021-08-10 19:26 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
> +    void validateEmail(String desc, String givenEmailRequest, EmailValidationResponse expectedEmailResponse) {
description도 괜찮을 것 같아요😊

2021-08-10 19:26 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
> +                .extracting(response -> response.as(EmailValidationResponse.class, restAssuredObjectMapper))
#25 PR이 적용되면 object mapper는 없어도 되겠죠?ㅎㅎ 저는 extracting도 좋지만 then 안에서 actualResponse.as의 형태로 받는 것도 좋은 거 같아요ㅎㅎ

2021-08-10 19:26 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
> +    @MethodSource
메서드 이름이 같으면 '@MethodSource' 안에 provider를 지정해주지 않아도 자동으로 맵핑되나요? 신기하네요ㅎㅎ

2021-08-10 19:26 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
> +    static Stream<Arguments> validateEmailTest() {
validateEmailProvider는 어떨까요?ㅎㅎ 인수테스트 작성 컨벤션이었던 것 같긴한데 서비스에도 동일한 네이밍 규칙을 사용하는 것도 괜찮을 것 같아요♡

2021-08-11 04:01 UTC, min27604 commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
> +    void validateEmail(String desc, String givenEmailRequest, EmailValidationResponse expectedEmailResponse) {
넵 적용해놓을게요!

2021-08-11 04:02 UTC, min27604 commented on src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
> +    static Stream<Arguments> validateEmailTest() {
이거 처음에 메서드 명 대충 짓고 바꿔야지 했던 부분인데ㅠㅡㅠ 깜빡했네요. 감사합니다!

2021-08-11 04:04 UTC, min27604 commented on src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
> +    @MethodSource
네 명시해주지 않으면 테스트 메서드와 같은 메서드 명을 찾더라구요!

2021-08-11 07:33 UTC, Dae-Hwa requested changes
새리 너무 수고 많으셨어요

처음에 이렇게 많이 적을라고 안 했는데 리뷰가 꽤 많아졌네요~ㅋㅋㅋ

이상한거 있으면 바로 멘션해주세요~!

2021-08-11 07:33 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
> +@Validated
`@Validated` 어노테이션은 `@Valid`랑 달라요. `@Validated`는 스프링에서 관리하는거고 `@Valid`는 jakarta bean validation에서 관리하는겁니다.
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/validation/annotation/Validated.html
https://www.baeldung.com/spring-valid-vs-validated

둘 중 어느걸 쓰느냐는 추후에 정해야겠지만, 특수한 상황이 아니라면 `@Valid` 를 쓰는게 지금은 더 좋을 것 같아요.

참고로 저는 `@Validated`를 리스트 형태를 검증할때 써봤던 것 같아요
https://github.com/alsqhd/issue-tracker/blob/be%2Fmain/be/issue-tracker-be/src/main/java/com/codesquad/issuetracker/issue/controller/IssueController.java
이렇게요

2021-08-11 07:33 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/service/UserService.java
> +    public EmailValidationResponse validateEmail(@Email String email) {
`@Email` 어노테이션이 여기서도 작동하나요??

2021-08-11 07:33 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/service/UserService.java
> +            return EmailValidationResponse.builder().existingEmail(true).build();
is 붙여주는게 좋을지 아직도 헷갈리네요 ㅋㅋㅋ

2021-08-11 07:33 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
@janeljs 이런 부분 인덴트 안 바꾸기로 했었죠?

2021-08-11 07:33 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
> +        TEST_USER = User.of("email@email.com");
이것 때문에 제대로 작동이 안 되네요

2021-08-11 07:33 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
> +        userRepository.save(User.of(1L, "nickname", "username", "existing@email.com", null, null));
더미 데이터 미리 넣는 것은 좋은 것 같습니다.
다만, 이것 때문에 제대로 동작하지 않는 테스트가 생겼네요.

그리고 id는 비워놓아야 하지 않나요?? JPA는 잘 인식해주나보네요

2021-08-11 07:33 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/service/UserService.java
> +        return EmailValidationResponse.builder().existingEmail(false).build();
이런 부분은 true나 false로만 이루어질테니 팩토리 메소드로 만들어도 괜찮을 것 같네요

2021-08-11 07:33 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
> +    }
Mockito를 활용해주셨네요!
서비스에 이메일이 있는지 판단하는 고유한 로직이 있으니 단위테스트를 작성해주신 것도 좋은 선택인 것 같아요

2021-08-11 07:33 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
> +        then(actualResponse.as(ErrorResponse.class, restAssuredObjectMapper))
이 부분도 충돌 해결이 아직 안 된 것 같아요~

2021-08-11 16:18 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/user/controller/UserController.java
> +@Validated
제가 알아본 바로는 자바 오브젝트가 아닌 프리미티브 타입으로 들어오는 query parameter나 path variable(primitive type)의 유효성 검사를 위해서는 `@Validated`를 써야한다고 하더라구요. 사실 처음에는 `@Valid` 어노테이션으로 쿼리파라미터를 검사할 방법을 못 찾았다가 이런 글을 발견했습니다. 혹시 다른 방법 아시면 알려주세요!!!
https://medium.com/javarevisited/are-you-using-valid-and-validated-annotations-wrong-b4a35ac1bca4

2021-08-11 16:18 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/user/service/UserService.java
> +    public EmailValidationResponse validateEmail(@Email String email) {
여기 이거 착각하고 넣어뒀던걸.. 깜빡했네요 ㅎㅎ;;

2021-08-11 16:26 UTC, min27604 commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
> +        userRepository.save(User.of(1L, "nickname", "username", "existing@email.com", null, null));
수정했습니다.

2021-08-11 16:26 UTC, min27604 commented on src/test/java/com/postsquad/scoup/web/user/service/UserServiceTest.java
> +        TEST_USER = User.of("email@email.com");
수정했습니다.

2021-08-11 16:27 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/user/service/UserService.java
> +            return EmailValidationResponse.builder().existingEmail(true).build();
`isPresent()` 부분 말씀이실까요??

2021-08-11 17:05 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/user/service/UserService.java
> +            return EmailValidationResponse.builder().existingEmail(true).build();
`existingEmail ` 이요 ㅎㅎ

2021-08-11 21:41 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
넵! 제 취향은 그렇다고 말씀드렸는데 자율에 맡기기로 했던 것 같아요ㅎㅎ

2021-08-12 06:08 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
자율에 맡기면 커밋할때마다 변경점이 생겨서요 ㅠㅠ 이런건 반드시 정해야 되는 부분 같습니다

2021-08-12 06:56 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/user/controller/UserAcceptanceTest.java
저번 회의 때 컨벤션을 문서에 업데이트도 안 하고 취향 차이라고만 말이 되어 자율에 맡긴다고 이해했어요. 이것말고도 서로 다르게 이해하는 부분들이 있는거 같은데 이야기 나온다음 컨벤션으로  확정한 부분은 앞으로는 문서에 업데이트를 하는게 좋을 것 같네요

2021-08-12 15:25 UTC, Dae-Hwa approved these changes

2021-08-12 15:33 UTC, merged