[새리][3-1-1] 그룹 생성
Sc0up/scoup-backend pull request #75
Opened 2021-08-17 15:34 UTC by min27604

그룹 생성 기능 구현했습니다.
그룹에는 그룹 생성 시 필요한 `name`, `description`만 담도록 하였고 `GroupCreationRequest`를 받아 매퍼를 통해 그룹으로 변환, 저장하도록 구현하였습니다.

인수 테스트에는 정상 작동과 `GroupCreationRequest`의 유효성 검사를 테스트하였고 레포지토리 테스트에는 DB 제약조건을 테스트했습니다.

감사합니다.

2021-08-18 08:22 UTC, Dae-Hwa requested changes
고생많으셨습니다!

equals는 필요할때 다시 재정의해줘도 괜찮을 것 같아요

2021-08-18 08:22 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/group/controller/request/GroupCreationRequest.java
> +    public GroupCreationRequest(@NotEmpty String name, String description) {
이런 식으로 해결하셨군요 👍 고민 많이 하셨겠어요
나중에 중복되는 부분이 많아질때 base에 합치는걸 생각해보면 되겠네요

2021-08-18 08:22 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/group/controller/request/GroupCreationRequest.java
> +@EqualsAndHashCode(callSuper = true)
equals가 필요한 부분이 있었나요?
그리고 순서 맞춰주세요~!

2021-08-19 01:53 UTC, janeljs submitted a review, later dismissed

2021-08-19 01:53 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/group/mapper/GroupMapperTest.java
> +    void groupCreationRequestToGroup(GroupCreationRequest givenGroupCreationRequest, Group expectedGroup) {
왜 given이 없나 했는데 맵퍼 테스트였군요! when부분이 given 아닐까요? 새리랑 프레디는 어떻게 생각하세요? @Dae-Hwa @min27604

2021-08-19 05:01 UTC, Dae-Hwa commented on src/test/java/com/postsquad/scoup/web/group/mapper/GroupMapperTest.java
> +    void groupCreationRequestToGroup(GroupCreationRequest givenGroupCreationRequest, Group expectedGroup) {
제 생각은 groupCreationRequestToGroup를 테스트하는거면 when에도 groupCreationRequestToGroup가 와야 한다고 생각해요 when이 검증할 로직이니까요

2021-08-19 05:15 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/group/mapper/GroupMapperTest.java
> +    void groupCreationRequestToGroup(GroupCreationRequest givenGroupCreationRequest, Group expectedGroup) {
아 when이 검증할 로직이었죠! given이 검증할 로직이라고 헷갈렸네요ㅎㅎ

2021-08-19 05:17 UTC, janeljs commented on src/test/java/com/postsquad/scoup/web/group/mapper/GroupMapperTest.java
> +    void groupCreationRequestToGroup(GroupCreationRequest givenGroupCreationRequest, Group expectedGroup) {
지금이 좋은 것 같아요! 죄송해요 @min27604 😢

2021-08-19 08:49 UTC, min27604 commented on src/main/java/com/postsquad/scoup/web/group/controller/request/GroupCreationRequest.java
> +@EqualsAndHashCode(callSuper = true)
다른 클래스를 상속받은 클래스에 `@Data`를 넣게되면 슈퍼클래스에도 재정의 해줘야하더라구요! 순서는 수정하겠습니다!

2021-08-19 15:25 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/group/controller/request/GroupCreationRequest.java
> +@EqualsAndHashCode(callSuper = true)
상속시키는 상위 클래스에 equals 있지 않나요???
제가 이해를 잘 못한 것 같아요

2021-08-19 15:27 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/group/controller/request/GroupCreationRequest.java
> +@EqualsAndHashCode(callSuper = true)
equals를 사용할 일이 없는 것 아닌가 하는 것이었습니다.

2021-08-20 05:53 UTC, Dae-Hwa commented on src/main/java/com/postsquad/scoup/web/group/controller/request/GroupCreationRequest.java
> +@EqualsAndHashCode(callSuper = true)
없으면 warning이 뜬다

2021-08-20 05:53 UTC, Dae-Hwa approved these changes

2021-08-20 05:55 UTC, janeljs approved these changes

2021-08-20 05:55 UTC, merged